<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Pet Heaven-Dog & Cat Adoption</title>
		<meta charset="utf-8"/>
		<link rel="stylesheet" href="../css/styleAdoption.css"/>
		<script src="../script/scriptPetHeaven.js"></script>
	</head>
	<body onload="setDate()">
		<header>
			<a href="homePage.php"><img src="../images/Logo.png" alt="logo" class="logo"/></a>
			<!--Pets:http://4.bp.blogspot.com/-akRxXGd3MXo/UqxJcyhQFgI/AAAAAAAAA-Q/9fO5ypoxp5I/s1600/Cat_And_Dog_Cartoon_Image-918.png
				Clouds:http://www.sanjosefunerales.com/wp-content/uploads/2015/02/SanJose_Slider5_nube2.png
			-->
			<span class="name">Pet Heaven
				<span id="date"></span>
				<span id="time"></span>
			</span>
		</header>
		<aside>
			<ul class="menu">
				<li ><a href="homePage.php">Home</a></li>
				<li id="findpet">Find a pet
					<ul class="pet">
						<li><a href="FindaDog.php">Dog</a></li>
						<li><a href="FindaCat.php">Cat</a></li>
					</ul>
				</li>
				<li><a href="DogCare.php">Dog Care</a></li>
				<li><a href="CatCare.php">Cat Care</a></li>
				<li><a href="createAnAccount.php">Create an Account</a></li>
				<li><a href="LoginGiveAway.php">Have a pet to give away</a></li>
				<li><a href="LogOut.php">Log Out</a></li>
				<li><a href="Contact.php">Contact Us</a></li>
			</ul>
		</aside>